### PR TITLE
BLUI-3261 Upgrade to react native v0.70.0

### PR DESCRIPTION
**Pull request by daileytj**
Fixes BLUI-3261.

#### Changes proposed in this Pull Request:
- Update to react-native@0.70.0

#### To Test:
- `git clone git@github.com:brightlayer-ui/brightlayer-ui-cli.git -b feature/3261-upgrade-to-rn-70`
- `cd brightlayer-ui-cli`
- `yarn && yarn build && yarn link`
- open a new terminal with a directory to generate new projects in
- Test all 6 templates by generating new projects using the following commands (use defaults for unspecified options):
  - `blui new --framework=react-native --name=TestBlankRN70 --template=blank --alpha --language=javascript`
  - `blui new --framework=react-native --name=TestBlankTSRN70 --template=blank --alpha --language=typescript`
  - `blui new --framework=react-native --name=TestRoutingRN70 --template=routing --alpha --language=javascript`
  - `blui new --framework=react-native --name=TestRoutingTSRN70 --template=routing --alpha --language=typescript`
  - `blui new --framework=react-native --name=TestAuthRN70 --template=authentication --alpha --language=javascript`
  - `blui new --framework=react-native --name=TestAuthTSRN70 --template=authentication --alpha --language=typescript`
- Follow the CLI instructions to get the projects running and go through these projects on android and iOS to ensure they all build and function as expected

### CODE REVIEW

**Comment by jeffvg** [comment]
all the templates are good on iOS except for the error we talked about when selecting change password from menu...

image

**Comment by emclaug2** [comment]
I ran into some issues with the `yarn link` step above, but managed to get this command to work on a windows machine.

` yarn build:local --framework=react-native --name=TestBlankRN70 --template=blank --alpha --language=javascript` 

Basically the flags from all the 6 projects to test can be dropped in & replaced as-needed.

**Comment by emclaug2** [comment]
I'm walking through these on android now,
`yarn build:local --framework=react-native --name=TestBlankRN70 --template=routing--alpha --language=javascript` gave me an error.

[RN Routing JS Error.txt](https://github.com/brightlayer-ui/brightlayer-ui-cli/files/9852086/RN.Routing.JS.Error.txt)

**Comment by emclaug2** [comment]
> I'm walking through these on android now, `yarn build:local --framework=react-native --name=TestBlankRN70 --template=routing--alpha --language=javascript` gave me an error.
> 
> [RN Routing JS Error.txt](https://github.com/brightlayer-ui/brightlayer-ui-cli/files/9852086/RN.Routing.JS.Error.txt)

@jeffvg did the Routing & JS command work for you on ios?

**Comment by jeffvg** [comment]
> I'm walking through these on android now, `yarn build:local --framework=react-native --name=TestBlankRN70 --template=routing--alpha --language=javascript` gave me an error.
> 
> [RN Routing JS Error.txt](https://github.com/brightlayer-ui/brightlayer-ui-cli/files/9852086/RN.Routing.JS.Error.txt)
> 
> @jeffvg did the Routing & JS command work for you on ios?

looking again now but everything built & deployed fine with no errors or warnings for me. I did not try to run "build" alone

**Comment by jeffvg** [comment]
> I'm walking through these on android now, `yarn build:local --framework=react-native --name=TestBlankRN70 --template=routing--alpha --language=javascript` gave me an error.
> 
> [RN Routing JS Error.txt](https://github.com/brightlayer-ui/brightlayer-ui-cli/files/9852086/RN.Routing.JS.Error.txt)
> 
> @jeffvg did the Routing & JS command work for you on ios?

I'm running with gradle 7.5.1 and it looks like you are on 4.1.0 not sure. But this also might be a path deal on windows vs. Mac.

**Comment by emclaug2** [comment]
> I'm running with gradle 7.5.1 and it looks like you are on 4.1.0 not sure. But this also might be a path deal on windows vs. Mac.

Ah, this looks like a local config issue for me; I've got grandle 7.3.1 installed but my android studio isn't detecting it for some reason.  I'll keep playing with this on my end, but it sounds like this PR is in a good spot if both you & Tom got the templates to run.

**Comment by jeffvg** [comment]
> > I'm running with gradle 7.5.1 and it looks like you are on 4.1.0 not sure. But this also might be a path deal on windows vs. Mac.
> 
> Ah, this looks like a local config issue for me; I've got grandle 7.3.1 installed but my android studio isn't detecting it for some reason. I'll keep playing with this on my end, but it sounds like this PR is in a good spot if both you & Tom got the templates to run.

sorry for confusion...maybe I didn't mention my Android isn't working on my Mac. Only iOS currently works for me. I did notice this just now but have no clue why because a default RN project is the same..

image

**Pull request merged**
