### PR TITLE
Enforce valid template selection

### LINKED ISSUE #52: Enforce Valid Template Selection
#### Describe the desired behavior
CLI template selection should be limited to supported templates.  This applies to angular and react projects. 

#### Describe the current behavior
Users can enter whatever template they want through the `--template` flag.

#### Is this request related to a current issue?
No

### PR DESCRIPTION
**Pull request by daileytj**
Fixes #52.

#### Changes proposed in this Pull Request:
- Enforces valid template selection

#### To Test:
- Run the CLI new command with the `--template` flag
- If --template=<any valid template || 'file:'> then it will just work as normal
- If --template=<invalid template name> it will prompt the user to select a template as if they didn't use the template flag

### CODE REVIEW

**Comment by daileytj** [comment]
I'm not sure why I can't change the filename for the `pxblue-extensions.js` file, but anytime I do it breaks and there is no reference to where it is being used. I'd like to just change it in this PR, but we can write a bug to address it as well.

**Review by emclaug2 — CHANGES_REQUESTED** [review]
Can you try the `yarn build:local` command in this package?  I've added this for local testing. There's an error being thrown right now because the templateName is being checked for validity before it's set. 

image

**Review by emclaug2 — APPROVED** [review]
Works locally, invalid template name forces a template selection later in project creation.   Very nice.

**Comment by jeffvg** [comment]
looking at this now.

**Comment by jeffvg** [comment]
wondering how this was tested...
I cloned fresh cli
did yarn link
and ran
blui new --template file:/Users/e0458886/blui/react-cli-templates/authentication-typescript

so if the file template name has typo then what?

**Comment by daileytj** [comment]
If the file template has a typo then that's on the user. There's no way to validate a named local file since you can name it anything you want. As long as the template starts with `file:` its marked as valid

**Comment by daileytj** [comment]
@jeffvg you can look at the validation function to see what is considered valid https://github.com/brightlayer-ui/brightlayer-ui-cli/pull/118/files#diff-33f8c37f2cb09262ef1309f98566226ab90240aa07818c1ff3a7362885cadd14

**Review by jeffvg — APPROVED** [review]

**Pull request merged**
