### PR TITLE
Feature/increase budget

### PR DESCRIPTION
**Pull request by emclaug2**
#### Changes proposed in this Pull Request:
- Update angular budget so our auth templates will build without err. 

#### To Test:
- `yarn build:local` and make a new ng project w/ auth template, then run `cd [project-name] && yarn build`

### CODE REVIEW

**Comment by ektasawant** [comment]
Getting below error:

Screenshot 2022-03-18 at 10 55 12 AM

Steps I followed:
1. Run yarn build:local from root
2. Select angular framework with auth template
3. And cd [project-name] && yarn build

Am I missing anything?

**Comment by emclaug2** [comment]
> Steps I followed:
> 
> 1. Run yarn build:local from root
> 2. Select angular framework with auth template
> 3. And cd [project-name] && yarn build
> 
> Am I missing anything?

No these steps look good to me; this is weird.  Could you run these steps again from the dev branch to see if the issue persists?  Running these steps locally works for me; just make sure to run `yarn` when you initially clone or checkout the new branch.

**Comment by jeffvg** [comment]
seem ok for me

image

**Comment by ektasawant** [comment]
> ust make sure to run `yarn` when

Still getting error with fresh clone and run yarn command. But if it is working for Jeff then it must be issue at my end.

**Comment by jeffvg** [comment]
> > ust make sure to run `yarn` when
> 
> Still getting error with fresh clone and run yarn command. But if it is working for Jeff then it must be an issue at my end.

I did this the long way. yarn and yarn link. open terminal and run ```blui new angular``` select auth template and let it build

**Review by jeffvg — APPROVED** [review]

**Comment by daileytj** [comment]
Screen Shot 2022-03-18 at 2 46 45 PM

I'm getting the same errors as Ekta...

**Pull request merged**
